#!/usr/bin/env bash
# Display "Best School" 10 times and displays "Hi" for the 9th iteration

i=0

while [ $i -lt 10 ]; do
      echo "Best School"
      if [ $i -eq 8 ]; then
	  echo "Hi"
      fi
      i=$((i+1))
done
