#!/usr/bin/env bash
# Displays numbers from 1 to 20 and the following
# the string "bad luck from China" in the 4th loop
# the string "bad luck from Japan" in the 9th loop
# the string "bad luck from Italy" in the 17th loop

i=1

while [ $i -le 20 ]; do
    echo "$i"
    case "$i" in
	4)
	    echo "bad luck from China" ;;
	9)
	    echo "bad luck from Japan" ;;
	17)
	    echo "bad luck from Italy" ;;
    esac
    i=$((i+1))
done
